### ISSUE TITLE
Put version seperately

### ISSUE THREAD

**Issue by FranklinYu** [takeshixx/python-ssllabs#10]
Currently `setup.py` depends on `ssllabs` module, which wants `requests`. So when I install it before resolving the dependency it’s already asking for `requests`. A possible solution is not to put version in the module, or put it in a separate file so that `setup.py` can import only that file.

**Comment by takeshixx** [comment]
Fixed in 3c1f506e7d81011701a2c6c24790bcadfe574fae, thanks for the hint.
