### ISSUE TITLE
When error is raised there is None as error message

### ISSUE THREAD

**Issue by alchemyx** [takeshixx/python-ssllabs#3]
On line 299 there is:

`print('An error occured: {}'.format(_status.get('errors')))`

Altought everytime I get error from API (for example - timeout or unresolvable item) i don't have `errors`there is `statusMessage`. That line always returns when error occurs:

> An error occured: None

Pull request with explanation from API docs #4

**Comment by takeshixx** [comment]
Thanks for the pull request, I've merged it.
